#!/bin/bash

wdir=$PWD

# get conda environment
. /opt/scp/software/Anaconda2/5.2.0/etc/profile.d/conda.sh

destinationDir="/projects/cp/knkr256/projects/computational/dask/ICB-ml-training/structures"

# systems
count=1
scount=1

trainingData="tsa.txt"
test -f $trainingData && rm $trainingData
touch $trainingData

rm $wdir/structures/*

# activate kallisto env
conda activate f-kallisto

# number of Carbon bound ti Iridium
cPos=86

# systems from the literature
for i in $(cat names); do
	echo $i
	cd $i
	# dump relative barriers to bash array
	IFS=$'\n' read -d '' -r -a relativeBarriers < relative_energy
	IFS=$'\n' read -d '' -r -a chpos < positions
	idir=$PWD
	cd $idir
	if [ -d "ch_positions" ]; then
		cd ch_positions
		chdir=$PWD
		# CH positions: actual position in $k
		# Get all barriers
		for k in "${chpos[@]}"; do
			cd $k
			kdir=$PWD
			k=$(echo $k | sed "s#/##g")
			#for l in 1 2 3 4 5 6 7 8 9 19 20 21 22 23 24 25 26 27; do
			for l in 1; do
				cd ts${l}
				#########################
				cd xtb
				pwd
				sname=$(printf "%04d\n" $scount)
				cp xtbopt.xyz $destinationDir/${sname}.xyz
				let "scount=scount+1"
				cd $kdir
				######################### 
			done
			cd $chdir
		done
		## TS1
		ec=0
		for k in "${chpos[@]}"; do
		    echo "${chpos[$ec]}" "${relativeBarriers[$ec]}"
			k=$(echo $k | sed "s#/##g")
			#for l in 1 2 3 4 5 6 7 8 9 19 20 21 22 23 24 25 26 27; do
			for l in 1; do
			 name=$(printf "%04d\n" $count)
			 echo structures/${name}.xyz "${relativeBarriers[$ec]}" $i $k >> $wdir/$trainingData
			 let "count=count+1"
		    done
			let "ec=ec+1"
		done
	fi
 cd $wdir
done
conda activate ml
python removeHydrogen.py
